/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Profile = IDL.Record({
  'age' : IDL.Nat,
  'bio' : IDL.Text,
  'latitude' : IDL.Opt(IDL.Float64),
  'interests' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : Time,
  'updatedAt' : Time,
  'longitude' : IDL.Opt(IDL.Float64),
  'photo' : IDL.Opt(ExternalBlob),
  'isComplete' : IDL.Bool,
});
export const NotificationType = IDL.Variant({
  'newMatch' : IDL.Null,
  'tipReceived' : IDL.Null,
  'newMessage' : IDL.Null,
});
export const Notification = IDL.Record({
  'id' : IDL.Text,
  'notificationType' : NotificationType,
  'user' : IDL.Principal,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const Message = IDL.Record({
  'content' : IDL.Text,
  'sender' : IDL.Principal,
  'timestamp' : Time,
  'receiver' : IDL.Principal,
});
export const Tip = IDL.Record({
  'to' : IDL.Principal,
  'from' : IDL.Principal,
  'amount_e8s' : IDL.Nat,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearAllData' : IDL.Func([], [], []),
  'createOrUpdateProfile' : IDL.Func([Profile], [], []),
  'deleteProfile' : IDL.Func([IDL.Principal], [], []),
  'dislikeUser' : IDL.Func([IDL.Principal], [], []),
  'getActivityFeed' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(Notification, IDL.Nat))],
      ['query'],
    ),
  'getAllProfiles' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
  'getCallerProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getExploreProfiles' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
  'getMatches' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
  'getMessagesWithUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
  'getTipHistory' : IDL.Func([IDL.Principal], [IDL.Vec(Tip)], ['query']),
  'getTopTippedUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getTotalTips' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getUserCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isProfileComplete' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'likeUser' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  'markAllNotificationsAsRead' : IDL.Func([], [], []),
  'markNotificationAsRead' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([Profile], [], []),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'setProfilePicture' : IDL.Func([ExternalBlob], [], []),
  'tip' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Profile = IDL.Record({
    'age' : IDL.Nat,
    'bio' : IDL.Text,
    'latitude' : IDL.Opt(IDL.Float64),
    'interests' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : Time,
    'updatedAt' : Time,
    'longitude' : IDL.Opt(IDL.Float64),
    'photo' : IDL.Opt(ExternalBlob),
    'isComplete' : IDL.Bool,
  });
  const NotificationType = IDL.Variant({
    'newMatch' : IDL.Null,
    'tipReceived' : IDL.Null,
    'newMessage' : IDL.Null,
  });
  const Notification = IDL.Record({
    'id' : IDL.Text,
    'notificationType' : NotificationType,
    'user' : IDL.Principal,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const Message = IDL.Record({
    'content' : IDL.Text,
    'sender' : IDL.Principal,
    'timestamp' : Time,
    'receiver' : IDL.Principal,
  });
  const Tip = IDL.Record({
    'to' : IDL.Principal,
    'from' : IDL.Principal,
    'amount_e8s' : IDL.Nat,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearAllData' : IDL.Func([], [], []),
    'createOrUpdateProfile' : IDL.Func([Profile], [], []),
    'deleteProfile' : IDL.Func([IDL.Principal], [], []),
    'dislikeUser' : IDL.Func([IDL.Principal], [], []),
    'getActivityFeed' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(Notification, IDL.Nat))],
        ['query'],
      ),
    'getAllProfiles' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
    'getCallerProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getExploreProfiles' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
    'getMatches' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
    'getMessagesWithUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
    'getTipHistory' : IDL.Func([IDL.Principal], [IDL.Vec(Tip)], ['query']),
    'getTopTippedUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getTotalTips' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getUserCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isProfileComplete' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'likeUser' : IDL.Func([IDL.Principal], [IDL.Bool], []),
    'markAllNotificationsAsRead' : IDL.Func([], [], []),
    'markNotificationAsRead' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([Profile], [], []),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'setProfilePicture' : IDL.Func([ExternalBlob], [], []),
    'tip' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };