/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface Message {
  'content' : string,
  'sender' : Principal,
  'timestamp' : Time,
  'receiver' : Principal,
}
export interface Notification {
  'id' : string,
  'notificationType' : NotificationType,
  'user' : Principal,
  'isRead' : boolean,
  'message' : string,
  'timestamp' : Time,
}
export type NotificationType = { 'newMatch' : null } |
  { 'tipReceived' : null } |
  { 'newMessage' : null };
export interface Profile {
  'age' : bigint,
  'bio' : string,
  'latitude' : [] | [number],
  'interests' : Array<string>,
  'name' : string,
  'createdAt' : Time,
  'updatedAt' : Time,
  'longitude' : [] | [number],
  'photo' : [] | [ExternalBlob],
  'isComplete' : boolean,
}
export type Time = bigint;
export interface Tip {
  'to' : Principal,
  'from' : Principal,
  'amount_e8s' : bigint,
  'timestamp' : Time,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearAllData' : ActorMethod<[], undefined>,
  'createOrUpdateProfile' : ActorMethod<[Profile], undefined>,
  'deleteProfile' : ActorMethod<[Principal], undefined>,
  'dislikeUser' : ActorMethod<[Principal], undefined>,
  'getActivityFeed' : ActorMethod<[], Array<[Notification, bigint]>>,
  'getAllProfiles' : ActorMethod<[], Array<Profile>>,
  'getCallerProfile' : ActorMethod<[], [] | [Profile]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [Profile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getExploreProfiles' : ActorMethod<[], Array<Profile>>,
  'getMatches' : ActorMethod<[], Array<Profile>>,
  'getMessagesWithUser' : ActorMethod<[Principal], Array<Message>>,
  'getNotifications' : ActorMethod<[], Array<Notification>>,
  'getProfile' : ActorMethod<[Principal], [] | [Profile]>,
  'getTipHistory' : ActorMethod<[Principal], Array<Tip>>,
  'getTopTippedUsers' : ActorMethod<[], Array<Principal>>,
  'getTotalTips' : ActorMethod<[Principal], bigint>,
  'getUserCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [Profile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isProfileComplete' : ActorMethod<[Principal], boolean>,
  'likeUser' : ActorMethod<[Principal], boolean>,
  'markAllNotificationsAsRead' : ActorMethod<[], undefined>,
  'markNotificationAsRead' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[Profile], undefined>,
  'sendMessage' : ActorMethod<[Principal, string], undefined>,
  'setProfilePicture' : ActorMethod<[ExternalBlob], undefined>,
  'tip' : ActorMethod<[Principal, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];